# Generated by Django 3.1.7 on 2021-03-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Convinence_fee',
            field=models.FloatField(default=100),
        ),
    ]
