# Generated by Django 3.1.7 on 2021-03-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionApp', '0003_auto_20210314_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Convinence_fee',
            field=models.IntegerField(blank=True, default=100),
        ),
    ]
