# Generated by Django 3.1.7 on 2021-03-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionApp', '0006_auto_20210314_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testregistration',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
