# Generated by Django 3.1.7 on 2021-03-14 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionApp', '0007_auto_20210314_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CURRENCY', models.CharField(max_length=100)),
                ('GATEWAYNAME', models.CharField(max_length=100)),
                ('RESPMSG', models.CharField(max_length=100)),
                ('BANKNAME', models.CharField(max_length=100)),
                ('PAYMENTMODE', models.CharField(max_length=100)),
                ('MID', models.CharField(max_length=100)),
                ('RESPCODE', models.CharField(max_length=100)),
                ('TXNID', models.CharField(max_length=100)),
                ('TXNAMOUNT', models.CharField(max_length=100)),
                ('ORDERID', models.CharField(max_length=100)),
                ('STATUS', models.CharField(max_length=100)),
                ('BANKTXNID', models.CharField(max_length=100)),
                ('TXNDATE', models.CharField(max_length=100)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdmissionApp.testregistration')),
            ],
        ),
    ]
