# Generated by Django 3.1.7 on 2021-03-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionApp', '0010_remove_payment_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testregistration',
            old_name='class_of_admission',
            new_name='CLASSOFADMISSION',
        ),
        migrations.RenameField(
            model_name='testregistration',
            old_name='date_of_birth',
            new_name='DATEOFBIRTH',
        ),
        migrations.RenameField(
            model_name='testregistration',
            old_name='first_name',
            new_name='FATHERFIRSTNAME',
        ),
        migrations.RenameField(
            model_name='testregistration',
            old_name='last_name',
            new_name='FIRSTNAME',
        ),
        migrations.RenameField(
            model_name='testregistration',
            old_name='image',
            new_name='IMAGE',
        ),
        migrations.RenameField(
            model_name='testregistration',
            old_name='marksheet',
            new_name='MARKSHEET',
        ),
        migrations.RenameField(
            model_name='testregistration',
            old_name='middle_name',
            new_name='MIDDLENAME',
        ),
        migrations.RenameField(
            model_name='testregistration',
            old_name='phone',
            new_name='PHONE',
        ),
        migrations.RenameField(
            model_name='testregistration',
            old_name='uploaded_at',
            new_name='UPLOADEDAT',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='CURRENCY',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='MID',
        ),
        migrations.AddField(
            model_name='testregistration',
            name='LASTNAME',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
